### ISSUE TITLE
When do we get macOS Support?

### ISSUE THREAD

**Issue by TheRealJayjayli** [ABSoftwareOfficial/ABSoftware.ABParser#1]

**Comment by Alex-ABWorld** [comment]
MacOS support when I work out how to compile to it.

**Comment by TheRealJayjayli** [comment]
get Xcode

**Comment by Alex-ABWorld** [comment]
1. On Windows?
2. For C++?
3. Using our existing infrastructure?

**Comment by TheRealJayjayli** [comment]
don't you dare close this

**Comment by TheRealJayjayli** [comment]
reopen now

**Comment by Alex-ABWorld** [comment]
No, please don't ruin this project with this issue. MacOS support will come sometime, I promise.

**Comment by TheRealJayjayli** [comment]
ok

Idk what this even does

**Comment by Alex-ABWorld** [comment]
I know. So you don't need it.
